config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile

  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
  has_many :posts
  has_many :communities, through: :subscriptions
  has_many :comments

  validates_presence_of :first_name, :last_name, :username

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_presence_of :message, :account_id, :post_id
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account

  validates_presence_of :url, :name, :rules
  
  has_many :posts 
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :account
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :community
  
  validates_presence_of :title, :body, :account_id, :community_id

  has_many :comments

  has_rich_text :body

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :community  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new comment_params
    @comment.account_id = current_account.id
    
    respond_to do |format|
      format.js {
        if @comment.save
          @comments = Comment.where(post_id: @comment.post_id)
          render "comments/create"
        else
          #unable to save
        end
      }
    end
  end

  def comment_params
    params.require(:comment).permit(:message, :post_id)
  end
  
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: [ :index, :show ]
  before_action :set_community, only: [:show]

  def index
    @communities = Community.all
  end

  def show
    @posts = @community.posts
    @subscriber_count = @community.subscribers.count
    @is_subscriber = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
    @subscription = Subscription.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new community_values
    @community.account_id = current_account.id

    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_values
    params.require(:community).permit(:name, :url, :summary, :rules)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [ :index, :show ]
  before_action :set_post, only: [:show]
  before_action :auth_subscriber, only: [:new]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
  end

  def create
    @post = Post.new post_values
    @post.account_id = current_account.id
    @post.community_id = params[:community_id]

    if @post.save
      redirect_to community_path(@post.community_id)
    else
      @community = Community.find(params[:community_id])
      render :new
    end
  end

  private

  def set_post
    @post = Post.includes(:comments).find(params[:id])
  end

  def auth_subscriber
    unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?
      redirect_to root_path, flash: { danger: "You are not authorized to view this page" }
    end
  end
  

  def post_values
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController


  def index
    @communities = Community.all.limit(5)
    @posts = Post.order(id: :desc).limit(20)
  end

  def profile
    @profile = Account.find_by_username params[:username]
    @posts = @profile.posts
  end
  
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.account_id = current_account.id
    @subscription.save

    redirect_to community_path(@subscription.community_id)

  end

  def subscription_params
    params.require(:subscription).permit(:community_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/create.js.erb
console.log("comment created...");

document.getElementById("post-comments").innerHTML = "<%= escape_javascript(render Posts::Comment::CommentComponent.new(comments: @comments)) %>"

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @community do |form| %>
      <div class="form-group">
        <%= label_tag :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :url %>
        <%= form.text_field :url, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :summary %>
        <%= form.text_area :summary, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :rules %>
        <%= form.text_area :rules, class: "form-control" %>
      </div>

      <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/communities/index.html.erb
<% if account_signed_in? %>
  <div class="float-right">
    <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>

<% if @communities.size > 0 %>
  <% @communities.each do |community| %>
    <div class="card">
      <h3><%= link_to community.name, community %></h3>
      <%= simple_format community.rules %>
    </div>
  <% end %>
<% else %>
  <h2>No communities to display</h2>
<% end %>

app/views/communities/new.html.erb
<h2>New Community</h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<div class="row mb-4">
  <div class="col-sm-8">
    <h2><%= @community.name %></h2>
  </div>
  <div class="col-sm-4">
    <% if @is_subscriber %>
      <%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-right" %>
    <% else %>
      <%= render Subscribe::ButtonComponent.new(subscription: @subscription, community: @community) %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-8">
    <%= render Posts::ListComponent.new(posts: @posts) %>
  </div>
  <div class="col-sm-4">
    <div class="card p-3">
      <p class="h5">About this community</p>
      <p class="mt-2"><%= @community.summary %></p>
      
      <p><%= pluralize @subscriber_count, "member" %></p>
    </div>
    <small>
      <%= simple_format @community.rules %>
    </small>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if account_signed_in? %>
      <%= render Core::Header::HeaderComponent.new(signed_in: true, account: current_account ) %>
    <% else %>
      <%= render Core::Header::HeaderComponent.new(signed_out: true) %>
    <% end %>

    <section class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 pt-4">
            <%= yield %>
          </div>
        </div>
      </div>
    </section>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-8">
    <%= form_for [@community, @post] do |form| %>
      <div class="form-group">
        <%= label_tag :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :body %>
        <%= form.rich_text_area :body, class: "form-control" %>
      </div>

      <%= form.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<%= @post.body %>

<div id="post-comments">
  <%= render Posts::Comment::CommentComponent.new(comments: @post.comments) %>
</div>


<h5>Leave a comment</h5>
<%= form_for @comment, remote: true do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.text_area :message, placeholder: "Your comment goes here", class: "form-control" %>
  <%= f.submit "Submit comment", class: "btn btn-success btn-lg mt-3" %>
<% end %>